"""first commit

Revision ID: 0001
Revises:
Create Date: 2026-02-07 23:02:46.157421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('entity', sa.SmallInteger(), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'grade'),
    sa.UniqueConstraint('id')
    )
    op.create_table('days',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, cycle=True), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_ns', sa.Boolean(), nullable=False),
    sa.Column('is_teacher', sa.Boolean(), nullable=False),
    sa.Column('is_parent', sa.Boolean(), nullable=False),
    sa.Column('default_child', sa.SmallInteger(), nullable=True),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password', sa.LargeBinary(length=255), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('ref', sa.String(length=255), nullable=True),
    sa.Column('schedule', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['schedule'], ['schedules.id'], onupdate='SET NULL', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'chat_id')
    )
    op.create_index(op.f('ix_users_chat_id'), 'users', ['chat_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('day_id', sa.SmallInteger(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homeworks',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.SmallInteger(), nullable=False),
    sa.Column('homework', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homeworks')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_users_chat_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('days')
    op.drop_table('schedules')
    # ### end Alembic commands ###