"""first commit

Revision ID: 3ebab24bb9b7
Revises: 
Create Date: 2024-11-25 21:15:30.311372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3ebab24bb9b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
                    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
                    sa.Column('entity', sa.SmallInteger(), nullable=False),
                    sa.Column('grade', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'grade'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('days',
                    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
                    sa.Column('schedule_id', sa.SmallInteger(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('lessons',
                    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
                    sa.Column('day_id', sa.SmallInteger(), nullable=False),
                    sa.Column('number', sa.SmallInteger(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('room', sa.String(length=50), nullable=True),
                    sa.ForeignKeyConstraint(['day_id'], ['days.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('homeworks',
                    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
                    sa.Column('lesson_id', sa.SmallInteger(), nullable=False),
                    sa.Column('homework', sa.String(length=255), nullable=False),
                    sa.Column('image', sa.String(length=255), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], onupdate='CASCADE', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('users', "isadmin", new_column_name='is_admin', existing_type=sa.SMALLINT(), type_=sa.Boolean(),
                    nullable=False, postgresql_using="CASE WHEN isadmin=0 THEN FALSE ELSE TRUE END")
    op.alter_column('users', "isns", new_column_name='is_ns', existing_type=sa.SMALLINT(), type_=sa.Boolean(),
                    nullable=False, postgresql_using="CASE WHEN isns=0 THEN FALSE ELSE TRUE END")
    op.alter_column('users', "isteacher", new_column_name='is_teacher', existing_type=sa.SMALLINT(), type_=sa.Boolean(),
                    nullable=False, postgresql_using="CASE WHEN isteacher=0 THEN FALSE ELSE TRUE END")
    op.alter_column('users', "isparent", new_column_name='is_parent', existing_type=sa.SMALLINT(), type_=sa.Boolean(),
                    nullable=False, postgresql_using="CASE WHEN isparent=0 THEN FALSE ELSE TRUE END")
    op.alter_column('users', "defaultchild", new_column_name='default_child', existing_type=sa.Integer(),
                    type_=sa.SmallInteger(), nullable=True)
    op.alter_column('users', "clas", new_column_name='grade', existing_type=sa.Integer(), type_=sa.String(length=50),
                    nullable=True)
    op.add_column('users', sa.Column('schedule', sa.SmallInteger(), nullable=True))
    op.add_column('users',
                  sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users',
                  sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'tgid', new_column_name='chat_id', type_=sa.BigInteger(), nullable=False)
    # op.alter_column('users', 'id',
    #                 existing_type=sa.INTEGER(),
    #                 server_default=sa.Identity(always=True, start=1, cycle=True),
    #                 existing_nullable=False)
    op.alter_column('users', 'login',
                    existing_type=sa.VARCHAR(length=4368),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('users', 'password',
                    existing_type=sa.VARCHAR(length=4368),
                    type_=sa.LargeBinary(length=255),
                    existing_nullable=True, postgresql_using="convert_to(password, 'LATIN1')")
    op.alter_column('users', 'blocked',
                    existing_type=sa.VARCHAR(length=4368),
                    type_=sa.Boolean(),
                    nullable=False, postgresql_using="CASE WHEN blocked='False' THEN FALSE ELSE TRUE END")
    op.alter_column('users', 'ref',
                    existing_type=sa.VARCHAR(length=4368),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('users', 'name',
                    existing_type=sa.VARCHAR(length=4368),
                    type_=sa.String(length=255),
                    nullable=False)
    op.alter_column('users', 'username',
                    existing_type=sa.VARCHAR(length=4368),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.create_index(op.f('ix_users_chat_id'), 'users', ['chat_id'], unique=False)
    op.create_foreign_key(None, 'users', 'schedules', ['schedule'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    op.drop_column('users', 'greet_notification')
    op.drop_column('users', 'time_to_greet')
    op.drop_column('users', 'duty_notification')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homeworks')
    op.drop_table('lessons')
    op.drop_table('days')
    op.drop_table('schedules')
    # ### end Alembic commands ###
