"""first commit2

Revision ID: 9d779c8f40f2
Revises: 9923db48c0ac
Create Date: 2024-11-25 22:08:35.649517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d779c8f40f2'
down_revision: Union[str, None] = '9923db48c0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, cycle=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
