from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # broadcast
    op.create_table(
        "broadcasts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PROCESSING",
                "COMPLETED",
                "CANCELED",
                "DELETED",
                "ERROR",
                name="broadcast_status"
            ),
            nullable=False
        ),
        sa.Column(
            "audience",
            sa.Enum(
                "ALL",
                "PARENTS",
                "TEACHERS",
                "NS",
                "ADMINS",
                name="broadcast_audience"
            ),
            nullable=False
        ),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failed_count", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id")
    )
    op.create_index(op.f("ix_broadcasts_status"), "broadcasts", ["status"], unique=False)

    op.create_table(
        "broadcast_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("broadcast_id", sa.Integer(), nullable=False),
        sa.Column("user_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "SENT",
                "FAILED",
                "EDITED",
                "DELETED",
                "PENDING",
                name="broadcast_message_status"
            ),
            nullable=False
        ),
        sa.ForeignKeyConstraint(["broadcast_id"], ["broadcasts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id")
    )
    op.create_index(
        op.f("ix_broadcast_messages_broadcast_id"),
        "broadcast_messages",
        ["broadcast_id"],
        unique=False
    )
    op.create_index(
        op.f("ix_broadcast_messages_status"), "broadcast_messages", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_broadcast_messages_user_telegram_id"),
        "broadcast_messages",
        ["user_telegram_id"],
        unique=False
    )

    # schedule
    op.create_table(
        "schedules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("COMMON", "TEACHER", "ROOM", name="schedule_type"),
            nullable=False
        ),
        sa.Column("grade", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_schedules_type"), "schedules", ["type"], unique=False)

    op.create_table("schedules_extra",
                    sa.Column("id", sa.Integer(), nullable=False),
                    sa.Column("year_photo_id", sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint("id")
                    )

    op.create_table(
        "days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.Enum(
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                "SATURDAY",
                "SUNDAY",
                name="week_day"
            ),
            nullable=False
        ),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_days_schedule_id"), "days", ["schedule_id"], unique=False)

    op.create_table("lessons",
                    sa.Column("id", sa.Integer(), nullable=False),
                    sa.Column("day_id", sa.Integer(), nullable=False),
                    sa.Column("number", sa.Integer(), nullable=False),
                    sa.Column("name", sa.String(length=255), nullable=True),
                    sa.Column("room", sa.String(length=50), nullable=True),
                    sa.ForeignKeyConstraint(["day_id"], ["days.id"], ondelete="CASCADE"),
                    sa.PrimaryKeyConstraint("id")
                    )
    op.create_index(op.f("ix_lessons_day_id"), "lessons", ["day_id"], unique=False)

    op.create_table(
        "homeworks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=255), nullable=False),
        sa.Column("image", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False
        ),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_homeworks_lesson_id"), "homeworks", ["lesson_id"], unique=False)

    # user
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("referral_code", sa.String(length=64), nullable=True),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("role", sa.Enum("USER", "ADMIN", "DEV", name="user_role"), nullable=False),
        sa.Column("grade", sa.String(length=50), nullable=False),
        sa.Column("is_ns", sa.Boolean(), nullable=False),
        sa.Column("is_teacher", sa.Boolean(), nullable=False),
        sa.Column("is_parent", sa.Boolean(), nullable=False),
        sa.Column("default_child", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=255), nullable=True),
        sa.Column("password", sa.LargeBinary(length=255), nullable=True),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            onupdate="SET NULL",
            ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_users_referral_code"), "users", ["referral_code"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_homeworks_lesson_id"), table_name="homeworks")
    op.drop_table("homeworks")
    op.drop_index(op.f("ix_lessons_day_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_referral_code"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_days_schedule_id"), table_name="days")
    op.drop_table("days")
    op.drop_index(op.f("ix_broadcast_messages_user_telegram_id"), table_name="broadcast_messages")
    op.drop_index(op.f("ix_broadcast_messages_status"), table_name="broadcast_messages")
    op.drop_index(op.f("ix_broadcast_messages_broadcast_id"), table_name="broadcast_messages")
    op.drop_table("broadcast_messages")
    op.drop_table("schedules_extra")
    op.drop_index(op.f("ix_schedules_type"), table_name="schedules")
    op.drop_table("schedules")
    op.drop_index(op.f("ix_broadcasts_status"), table_name="broadcasts")
    op.drop_table("broadcasts")
    # ### end Alembic commands ###
